name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R version ${{ matrix.config.r }})

    strategy: 
      matrix:
        config:
          - {os: ubuntu-16.04,   r: '3.6.1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with: 
          r-version: ${{ matrix.config.r }}


      - name: Update packages
        run: sudo apt-get -y update

      - name: Install libcurl (to install from source)
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install gdal (to use R librar sf)
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

        