name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy: 
      matrix:
        config:
          - {os: ubuntu-16.04,   r: '3.6.1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with: 
          r-version: ${{ matrix.config.r }}

        