name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    
    runs-on: ${{ matrix.config }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy: 
      matrix:
        config:
          - {os: ubuntu-16.04,   r: '3.6.1'}

      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      steps:
        - uses: actions/checkout@v2

        - name: Run a one-line script
          run: echo Hello, world!

        