name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R version ${{ matrix.config.r }})

    strategy: 
      matrix:
        config:
          - {os: ubuntu-16.04,   r: '3.6.1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@master
        with: 
          r-version: ${{ matrix.config.r }}


      # Steps to update/install Ubuntu packages
      - name: Update packages
        run: sudo apt-get -y update

      - name: Install libcurl (to install R libraries from source)
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install gdal (to use R library sf)
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev


      # Steps to install R packages
      - name: Install necessary R packages and dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "testthat", "covr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}


      # After success
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}